# Generated by Django 6.0.3 on 2026-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsearch',
            name='exam_pattern',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicsearch',
            name='preparation_guidance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicsearch',
            name='previous_papers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
